kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pensjon-opptjening-afp-api
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io/popp/api
    - name: POPP_API_ID
      value: dev-fss.pensjonopptjening.pensjon-popp-q2
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_API_ID
      value: dev-fss.pdl.pdl-api
    - name: SCOPE_BEREGN_READ
      value: afp.beholdningsgrunnlag.beregn.read
    - name: SCOPE_BEREGN_READ_EKSTERN
      value: nav:pensjonopptjening:ekstern.afp.beholdningsgrunnlag.beregn.read
    - name: SCOPE_SIMULER_READ
      value: afp.beholdningsgrunnlag.simuler.read
    - name: SCOPE_SIMULER_READ_EKSTERN
      value: nav:pensjonopptjening:ekstern.afp.beholdningsgrunnlag.simuler.read
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: ekstern.afp.beholdningsgrunnlag.beregn.read #nav:pensjonopptjening:ekstern.afp.beholdningsgrunnlag.beregn.read
          enabled: true
          product: pensjonopptjening
          consumers:
            - name: NAV
              orgno: "889640782"
            - name: KLP
              orgno: "938708606"
            - name: SPK
              orgno: "982583462"
            - name: STOREBRAND
              orgno: "931936492"
        - name: ekstern.afp.beholdningsgrunnlag.simuler.read  #nav:pensjonopptjening:ekstern.afp.beholdningsgrunnlag.simuler.read
          enabled: true
          product: pensjonopptjening
          consumers:
            - name: NAV
              orgno: "889640782"
            - name: KLP
              orgno: "938708606"
            - name: SPK
              orgno: "982583462"
            - name: STOREBRAND
              orgno: "931936492"
  ingresses:
    - https://pensjon-opptjening-afp-api.intern.dev.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: tjenestepensjon-simulering
          namespace: pensjonskalkulator
          cluster: dev-fss
          permissions:
            roles:
              - afp.beholdningsgrunnlag.simuler.read
        - application: pensjon-opptjening-afp-api
          permissions:
            roles:
              - afp.beholdningsgrunnlag.beregn.read
              - afp.beholdningsgrunnlag.simuler.read
    outbound:
      external:
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        cascadingDelete: true
        diskAutoresize: true
        #pointInTimeRecovery: true
        name: pensjon-opptjening-afp-api-db
        tier: db-custom-1-3840
        databases:
          - name: pensjon-opptjening-afp-api-db
            envVarPrefix: DATABASE
