kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pensjon-opptjening-afp-api
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io/popp/api
    - name: POPP_API_ID
      value: dev-fss.pensjonopptjening.pensjon-popp-q2
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_API_ID
      value: dev-fss.pdl.pdl-api
  azure:
#    sidecar:
#      enabled: true
#      autoLogin: true
    application:
      enabled: true
#      allowAllUsers: false
#      claims:
#        groups:
#          - id: "7ef907b4-ec9f-47dd-ab41-4e54ba32ceb1" #AAD pensjonopptjening testgruppe
  ingresses:
    - https://pensjon-opptjening-afp-api.intern.dev.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: tjenestepensjon-simulering
          namespace: pensjonskalkulator
          cluster: dev-fss
    outbound:
      external:
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
