name: Bygg branch and create image

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!main'
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v3

      # JAVA 17
      - name: 'Java 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      # BYGGER DOCKER CONTAINER
      - name: 'Bygg og publiser docker image'
        run: |
          ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
